version: '3.1'
services:
  db:
    image: db-mysql
    container_name: my-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: demodb
    restart: always
